package craftvillage.datalayer.entities;
// Generated Mar 24, 2020, 3:56:15 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

import craftvillage.corelayer.utilities.ConstantParameter;

/**
 * AdCountry generated by hbm2java
 */
@Entity
@Table(name = "ad_country", schema = ConstantParameter._SCHEMA_NAME)
public class AdCountry implements java.io.Serializable {

	private int countryId;
	private String zipcode;
	private String countryName;
	@JsonIgnore
	private Set<AdProvince> adProvinces;

	public AdCountry() {
	}

	public AdCountry(int countryId) {
		this.countryId = countryId;
	}

	public AdCountry(int countryId, String zipcode, String countryName, Set<AdProvince> adProvinces) {
		this.countryId = countryId;
		this.zipcode = zipcode;
		this.countryName = countryName;
		this.adProvinces = adProvinces;
	}
	@OrderBy("countryId ASC")
	@Id
	@Column(name = "COUNTRY_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getCountryId() {
		return this.countryId;
	}

	public void setCountryId(int countryId) {
		this.countryId = countryId;
	}

	@Column(name = "ZIPCODE", length = 20)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "COUNTRY_NAME", length = 50)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}
	
	@OrderBy("provinceId ASC")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adCountry")
	public Set<AdProvince> getAdProvinces() {
		return this.adProvinces;
	}

	public void setAdProvinces(Set<AdProvince> adProvinces) {
		this.adProvinces = adProvinces;
	}

}
