package craftvillage.datalayer.entities;
// Generated Mar 24, 2020, 3:56:15 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

import craftvillage.corelayer.utilities.ConstantParameter;

/**
 * AdWard generated by hbm2java
 */
@Entity
@Table(name = "AD_WARD", schema = ConstantParameter._SCHEMA_NAME)
public class AdWard implements java.io.Serializable {

	private int wardId;
	private AdDistrict adDistrict;
	private String wardCode;
	private String wardName;
	@JsonIgnore
	private Set<Village> villages = new HashSet<Village>();
	public AdWard() {
	}

	public AdWard(int wardId) {
		this.wardId = wardId;
	}

	public AdWard(int wardId, AdDistrict adDistrict, String wardCode, String wardName) {
		this.wardId = wardId;
		this.adDistrict = adDistrict;
		this.wardCode = wardCode;
		this.wardName = wardName;
	}
	
	@Id
	@Column(name = "WARD_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getWardId() {
		return this.wardId;
	}

	public void setWardId(int wardId) {
		this.wardId = wardId;
	}
	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DISTRICT_ID")
	public AdDistrict getAdDistrict() {
		return this.adDistrict;
	}

	public void setAdDistrict(AdDistrict adDistrict) {
		this.adDistrict = adDistrict;
	}

	@Column(name = "WARD_CODE", length = 20)
	public String getWardCode() {
		return this.wardCode;
	}

	public void setWardCode(String wardCode) {
		this.wardCode = wardCode;
	}

	@Column(name = "WARD_NAME", length = 50)
	public String getWardName() {
		return this.wardName;
	}

	public void setWardName(String wardName) {
		this.wardName = wardName;
	}
	@OrderBy("villageId ASC")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adWard")
	public Set<Village> getVillages() {
		return villages;
	}

	public void setVillages(Set<Village> villages) {
		this.villages = villages;
	}

}
