package craftvillage.datalayer.entities;
// Generated Mar 10, 2020 9:28:01 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonFormat;
import craftvillage.corelayer.utilities.ConstantParameter;

/**
 * UrSession generated by hbm2java
 */
@Entity
@Table(name = "UR_SESSION", schema = ConstantParameter._SCHEMA_NAME)
public class UrSession implements java.io.Serializable {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
  private int id;

  @JsonBackReference
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "UR_ID")
  private UrUser urUser;

  @JsonFormat(pattern = "dd-MM-yyyy hh:mm:ss")
  @Column(name = "LOGIN_TIME")
  private Date loginTime;

  @Column(name = "SESSION_STRING", length = 120)
  private String sessionString;

  public UrSession() {}

  public UrSession(int id, UrUser urUser, Date loginTime, String sessionString) {
    this.id = id;
    this.urUser = urUser;
    this.loginTime = loginTime;
    this.sessionString = sessionString;
  }

  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public UrUser getUrUser() {
    return this.urUser;
  }

  public void setUrUser(UrUser urUser) {
    this.urUser = urUser;
  }

  public Date getLoginTime() {
    return this.loginTime;
  }

  public void setLoginTime(Date loginTime) {
    this.loginTime = loginTime;
  }

  public String getSessionString() {
    return this.sessionString;
  }

  public void setSessionString(String sessionString) {
    this.sessionString = sessionString;
  }

}
